---
# Get list of 
- name: "Check if Lifecycles dont already exist"
  shell: "hammer lifecycle-environment list | awk '{print $3}' | grep -v NAME"
  register: lc_list

# Create default Lifecycle
- name: "Post Configure | Configure Lifecycle - {{ lcname }}"
  become: "yes"
  shell: "hammer lifecycle-environment create --organization  '{{ orgname }}' --name '{{ lcname }}'
       --description '{{ lcdesc }}' --prior '{{ lcprior }}'"
  ignore_errors: "yes"
  when: lcname not in lc_list.stdout


