---
# Get list of 
- name: "Check if Lifecycles dont already exist"
  shell: "hammer lifecycle-environment list | awk '{print $3}' | grep -v NAME"
  register: lc_list

# Create default Lifecycle
- name: "Post Configure | Configure default Lifecycle"
  become: "yes"
  shell: "hammer lifecycle-environment create --organization  '{{ item.value.organization }}' --name '{{ item.key }}'
       --description '{{ item.value.description }}' --prior '{{ item.value.prior }}'"
  ignore_errors: "yes"
  when: item.key not in lc_list.stdout
  with_dict: "{{ configure_satellite_lifecycles }}"


