---


# Add foreman discovery
- name: "Post Configure | Add foreman discovery"
  shell: "{{ satellite_deployment_installer_cmd }} --enable-foreman-plugin-discovery --enable-foreman-plugin-openscap"
  ignore_errors: "yes"

- name: "Post Configure | Create scripting directory"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /root/satellite
    - /root/satellite/contrail
    - /root/satellite/openstack
    - /root/satellite/openshift
    - /root/satellite/maintenance_scripts
    - /root/satellite/templates

# Copy over scripts
- name: "Post Configure | Populate contrail scripts"
  copy:
    src: "{{ item }}"
    dest: /root/satellite/contrail
    owner: root
    mode: preserve
  with_fileglob:
       - "contrail/*"
  ignore_errors: "yes"

- name: "Post Configure | Populate openstack scripts"
  copy:
    src: "{{ item }}"
    dest: /root/satellite/openstack
    owner: root
    mode: preserve
  with_fileglob:
       - "openstack/*"
  ignore_errors: "yes"

- name: "Post Configure | Populate openshift scripts"
  copy:
    src: "{{ item }}"
    dest: /root/satellite/openshift
    owner: root
    mode: preserve
  with_fileglob:
       - "openshift/*"
  ignore_errors: "yes"

- name: "Post Configure | Populate maintenance_scripts"
  copy:
    src: "{{ item }}"
    dest: /root/satellite/maintenance_scripts
    owner: root
    mode: preserve
  with_fileglob:
       - "maintenance_scripts/*"
  ignore_errors: "yes"

# Replace with templates !
- name: "Post Configure | Copy over template scripts"
  copy:
    src: "{{ item }}"
    dest: /root/satellite/templates
    owner: root
    mode: preserve
  with_fileglob:
       - "templates/*"
  ignore_errors: "yes"

## Create the Templates
