---
- set_fact:
    org_syncplans: >
      {{ org_syncplans|d([])
         + [ {} | combine(item.0) | combine(item.1) ]
      }}
  with_subelements:
   - "{{ configure_satellite_organizations }}"
   - sync_plans

#- debug:
#    msg: " {{ item.syncplan }}"
#  with_items:
#   - "{{ org_syncplans }}"

# Create sync plans for organizations dictionary
- name: "Create sync plans"
  shell: > 
         hammer sync-plan create --name '{{item.syncplan}}' \
         --interval '{{ item.interval }}' \
         --enabled '{{ item.enabled }}' \
         --organization '{{ item.orgname }}' \ 
         --sync-date '{{ item.startdate }}' 
  ignore_errors: "yes"
  with_items: 
   - "{{ org_syncplans }}"

- name: "Add products to sync plan per org per syncplan"
  shell: >
         hammer product set-sync-plan --name '{{ item[1].product }}' \
         --sync-plan '{{ item[0].syncplan }}' \
          --organization '{{ item[0].orgname }}'
  ignore_errors: "yes"
  with_subelements:
    - "{{ org_syncplans }}"
    - products


